### ISSUE TITLE
Ability to remove a slot column

### ISSUE THREAD

**Issue by Daltonstudio** [juho-jaakkola/elgg-scheduling#10]
Hey Juho,

I changed the JS a little bit to give users the option to delete a slot.
It prevents the first 2 slots to be deleted, since we need at least 2 slots to have something to choose from.
It adds an elgg-icon-delete next to the title (at he moment I add them to the initial columns via js, because I didn't want to touch the form, but adding them to the form initialy would be better).

I still need to figure out how to recompute the title slot numbers when you delete, let's say the second column, but not the 4th. Look into it when I have some time.
Here  is the changed is file
https://github.com/Daltonmedia/elgg-scheduling/blob/remove-column/views/default/js/scheduling/table.js
Feel free to look into it and comment.
![schermafbeelding 2015-11-24 om 09 50 53](https://cloud.githubusercontent.com/assets/6113614/11361941/f1d98f40-9290-11e5-9259-2eeb7e43e6e9.png)

**Comment by juho-jaakkola** [comment]
Could you make a PR so it's easier to see what changes you've made to the code?

**Comment by juho-jaakkola** [comment]
Fixed in b2afa9a3b72ea986dab432f89d3fb0faf2ce5443
