### ISSUE TITLE
Wrong Date when safing without time

### ISSUE THREAD

**Issue by lweddewer** [juho-jaakkola/elgg-scheduling#3]
When creating and saving a schedule with a date but without filling in a time will result a pull for the time Thu 1/1/1970 01:00 .

Due to that fact that no row deleting is implemented It's not possible to delete this wrong.
May it's possible to add a column "delete" left with a checkbox in every row.

regards
lothar

**Comment by juho-jaakkola** [comment]
Yes, the plan is to add the possibility to delete a whole row.

In the mean time you can just remove values from all fields on a row. This should delete the row.

**Comment by samo78** [comment]
Could it be a solution to make the input field a drop-down of times (like in mobile calendars) so users do not enter wrong times? 

A default time slot (i.e. 12:00) could also help to avoid the saving one row with empty field scenario.

**Comment by juho-jaakkola** [comment]
This has been fixed in d3c0a0010f082954dcfead03cca12219fbc49111
